const FormValidatorLengths = {
  DEFAULT_MAX_INPUT_LENGTH: 255,
  MAX_TEXTAREA_LENGTH: 2000,
  PROJECTION_TECHNOLOGY_MAX_INPUT_LENGTH: 50, PROJECTION_TECHNOLOGY_MAX_DESCRIPTION_LENGTH: 200
};

export default FormValidatorLengths;
