security:
  jwt:
    header: X-Authorization
    prefix: "Bearer "
    expiration: 86400000
spring:
  application:
    name: cinema
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  messages:
    basename: messages
    encoding: UTF-8
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
server:
  servlet:
    context-path: /api
seeders:
  enabled: true
