security:
  jwt:
    header: X-Authorization
    prefix: "Bearer "
    expiration: 86400000
spring:
  application:
    name: cinema
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  messages:
    basename: messages
    encoding: UTF-8
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
server:
  servlet:
    context-path: /api

seeders:
  enabled: true

paypal:
  clientId: AcaNONs5LZmMmO_giskmyCmilm5QUoNKkcFdfpEvCDOe4J9LJtr68hyIlEU5SMzKHgxHaKStBYMV2zj3
  clientSecret: EPbfzf6P9NZ_ohCaghA9lSyYzmmO_ywkpTzi4aFhs8ZivdQCLA1DaihV5Gh2fPTs8SQP359zdjKGcNwh
  mode: sandbox
