spring:
  application:
    name: cinema
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: messages
    encoding: UTF-8
server:
  servlet:
    context-path: /api
seeders:
  enabled: true
